### ISSUE TITLE
Saving equations throughout runtime 

### ISSUE THREAD

**Issue by cobac** [MilesCranmer/SymbolicRegression.jl#33] opened 2021-06-17 17:20 UTC
Hey, thank you so much for all your work in this package.

I'm interesting in evaluating the performance of this algorithm overtime (i.e. saving the `hallOfFame` object after each iteration). Is there any way that I've missed of achieving this without modifying the source code?

Thanks!

**Comment by MilesCranmer** [comment] 2021-06-17 20:35
Awesome to hear you are liking it! There is the `recorder::Bool` option in `Options`, which you can also turn on by setting the environment variable `PYSR_RECORDER=1`. Then, `recorder_file::String` is the filename for this (a JSON file; default is `pysr_recorder.json`). This JSON file records everything, even each individual mutation, which is maybe too much info, but it's helpful for debugging the performance. Does that work?

Cheers,
Miles

**Comment by cobac** [comment] 2021-06-17 21:47
Thanks! (btw those options are undocumented I don't know if you were aware)

Hmm... I assume that'd be quite a bit of overhead (?). But I could benchmark in different runs how the loss function evolves over time vs the actual time. Great.

However, I've done a few test runs with `recorder = true` (with and without `recorder_file = ...`) but I can't find the .json file in my filesystem. Using  [8254be44] SymbolicRegression v0.6.9. I can reproduce this in a clean environment.

Thanks again.

**Comment by MilesCranmer** [comment] 2021-06-19 18:42
No problem. That functionality is still experimental since I wrote it for myself to debug specific use-cases of the software in a project I'm using it on, but I can see now that others would find this useful too!

> However, I've done a few test runs with recorder = true (with and without recorder_file = ...) but I can't find the .json file in my filesystem. Using [8254be44] SymbolicRegression v0.6.9. I can reproduce this in a clean environment.

Sorry, I see the bug. Just pushed a fix to master. It should work now.

**Comment by cobac** [comment] 2021-06-20 16:44
Thanks!

I see that the program is trying to save the record now. However, all runs are failing at some point with `ERROR: Inf not allowed to be written in JSON spec`. Si I assume the program is trying to save an equation before checking if it produces proper results. I am not familiar enough with the code base to know what's the best workaround, but I assume you must have encountered the same issue in your own testing (?)

I've tested with current master and bc7b81ff80681b469bac55394c03ec56831e48e1

**Comment by MilesCranmer** [comment] 2021-06-21 01:43
I’ve never seen that before. How are you running it? Do you have a MWE?

**Comment by cobac** [comment] 2021-06-21 10:22
I've created [this repository](https://github.com/cobac/SymbolicRegression-JSON-Inf-error) that reproduces the error with current master, all packages updated and  Julia 1.6.1. I can reproduce the error instantiating the Manifest.toml and including the .jl file. I'm runing Linux and I've tested with 1 thread and with multiple threads, but I don't think that should be relevant in this case.

I've noticed that it always fails when the progress meter is at 60%.

This is the stacktrace I get: 

```
ERROR: Inf not allowed to be written in JSON spec)                        
           Stacktrace:        
  [1] #write#78
    @ ~/.julia/packages/JSON3/PgKj8/src/write.jl:225 [inlined]
  [2] write(::StructTypes.NumberType, buf::Vector{UInt8}, pos::Int64, len::Int64, x::Float64)
    @ JSON3 ~/.julia/packages/JSON3/PgKj8/src/write.jl:225
  [3] write(::StructTypes.DictType, buf::Vector{UInt8}, pos::Int64, len::Int64, x::Dict{String, Any}; kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ JSON3 ~/.julia/packages/JSON3/PgKj8/src/write.jl:155
  [4] write(::StructTypes.DictType, buf::Vector{UInt8}, pos::Int64, len::Int64, x::Dict{String, Any})
    @ JSON3 ~/.julia/packages/JSON3/PgKj8/src/write.jl:146
  [5] write(::StructTypes.DictType, buf::Vector{UInt8}, pos::Int64, len::Int64, x::Dict{String, Any}; kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ JSON3 ~/.julia/packages/JSON3/PgKj8/src/write.jl:155
  [6] write(::StructTypes.DictType, buf::Vector{UInt8}, pos::Int64, len::Int64, x::Dict{String, Any})
    @ JSON3 ~/.julia/packages/JSON3/PgKj8/src/write.jl:146
  [7] write(::StructTypes.DictType, buf::Vector{UInt8}, pos::Int64, len::Int64, x::Dict{String, Any}; kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ JSON3 ~/.julia/packages/JSON3/PgKj8/src/write.jl:155
  [8] write
    @ ~/.julia/packages/JSON3/PgKj8/src/write.jl:146 [inlined]
  [9] write(io::IOStream, obj::Dict{String, Any}; kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ JSON3 ~/.julia/packages/JSON3/PgKj8/src/write.jl:32
 [10] write(io::IOStream, obj::Dict{String, Any})
    @ JSON3 ~/.julia/packages/JSON3/PgKj8/src/write.jl:30
 [11] (::SymbolicRegression.var"#58#90")(io::IOStream)
    @ SymbolicRegression ~/.julia/packages/SymbolicRegression/vSShw/src/SymbolicRegression.jl:572
 [12] open(::SymbolicRegression.var"#58#90", ::String, ::Vararg{String, N} where N; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base ./io.jl:330
 [13] open
    @ ./io.jl:328 [inlined]
 [14] macro expansion
    @ ~/.julia/packages/SymbolicRegression/vSShw/src/SymbolicRegression.jl:571 [inlined]
 [15] macro expansion
    @ ~/.julia/packages/SymbolicRegression/vSShw/src/Recorder.jl:8 [inlined]
 [16] _EquationSearch(::SymbolicRegression.../ProgramConstants.jl.SRDistributed, datasets::Vector{SymbolicRegression.../Dataset.jl.Dataset{Float64}}; niterations::Int64, options::Options{Tuple{typeof(+), typeof(-), typeof(*), typeof(/)}, Tuple{typeof(sin), typeof(cos), typeof(exp), typeof(sq), typeof(cb)}, L2DistLoss}, numprocs::Nothing, procs::Nothing, runtests::Bool)
    @ SymbolicRegression ~/.julia/packages/SymbolicRegression/vSShw/src/SymbolicRegression.jl:570
 [17] EquationSearch(datasets::Vector{SymbolicRegression.../Dataset.jl.Dataset{Float64}}; niterations::Int64, options::Options{Tuple{typeof(+), typeof(-), typeof(*), typeof(/)}, Tuple{typeof(sin), typeof(cos), typeof(exp), typeof(sq), typeof(cb)}, L2DistLoss}, numprocs::Nothing, procs::Nothing, multithreading::Bool, runtests::Bool)
    @ SymbolicRegression ~/.julia/packages/SymbolicRegression/vSShw/src/SymbolicRegression.jl:181
 [18] EquationSearch(X::Matrix{Float64}, y::Matrix{Float64}; niterations::Int64, weig
hts::Nothing, varMap::Nothing, options::Options{Tuple{typeof(+), typeof(-), typeof(*)
, typeof(/)}, Tuple{typeof(sin), typeof(cos), typeof(exp), typeof(sq), typeof(cb)}, L
2DistLoss}, numprocs::Nothing, procs::Nothing, multithreading::Bool, runtests::Bool)
    @ SymbolicRegression ~/.julia/packages/SymbolicRegression/vSShw/src/SymbolicRegre
ssion.jl:145
 [19] #EquationSearch#24
    @ ~/.julia/packages/SymbolicRegression/vSShw/src/SymbolicRegression.jl:157 [inlin
ed]

```

Thanks again and sorry for the bother.

**Comment by MilesCranmer** [comment] 2021-06-21 21:21
Thanks! Just pushed a fix in https://github.com/MilesCranmer/SymbolicRegression.jl/commit/124020d79db1c766e6e35863b68bcc2608312a3d; want to try it? (set `--project=[path_to_repo]` to use the non-versioned one)

**Closed** 2021-06-22 17:02 UTC
